// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: api/shorturl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shorturl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"` // Строковый идентификатор
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`   // URL для сокращения
	// *config.Config ;
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Идентификатор пользователя
	Del    bool   `protobuf:"varint,5,opt,name=del,proto3" json:"del,omitempty"`                    // флаг, удалён ли URL пользователем или нет
}

func (x *Shorturl) Reset() {
	*x = Shorturl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shorturl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shorturl) ProtoMessage() {}

func (x *Shorturl) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shorturl.ProtoReflect.Descriptor instead.
func (*Shorturl) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *Shorturl) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Shorturl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Shorturl) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Shorturl) GetDel() bool {
	if x != nil {
		return x.Del
	}
	return false
}

type ShorturlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // URL для сокращения
}

func (x *ShorturlResponse) Reset() {
	*x = ShorturlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShorturlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShorturlResponse) ProtoMessage() {}

func (x *ShorturlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShorturlResponse.ProtoReflect.Descriptor instead.
func (*ShorturlResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *ShorturlResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Our address book file is just one of these.
type Shorturls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl []*Shorturl `protobuf:"bytes,1,rep,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *Shorturls) Reset() {
	*x = Shorturls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shorturls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shorturls) ProtoMessage() {}

func (x *Shorturls) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shorturls.ProtoReflect.Descriptor instead.
func (*Shorturls) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *Shorturls) GetShorturl() []*Shorturl {
	if x != nil {
		return x.Shorturl
	}
	return nil
}

// List -.
type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    string `protobuf:"bytes,4,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`          // Строковый идентификатор
	OriginalUrl string `protobuf:"bytes,5,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // URL для сокращения
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *List) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *List) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// User -.
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DelLink []string `protobuf:"bytes,2,rep,name=del_link,json=delLink,proto3" json:"del_link,omitempty"`
	Urls    []*List  `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetDelLink() []string {
	if x != nil {
		return x.DelLink
	}
	return nil
}

func (x *User) GetUrls() []*List {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Static -.
type Static struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Static) Reset() {
	*x = Static{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Static) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Static) ProtoMessage() {}

func (x *Static) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Static.ProtoReflect.Descriptor instead.
func (*Static) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{5}
}

type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl *Shorturl `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *PostRequest) GetShorturl() *Shorturl {
	if x != nil {
		return x.Shorturl
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *ShorturlResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error  string            `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *PostResponse) GetResult() *ShorturlResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PostResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LongLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl *Shorturl `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *LongLinkRequest) Reset() {
	*x = LongLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongLinkRequest) ProtoMessage() {}

func (x *LongLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongLinkRequest.ProtoReflect.Descriptor instead.
func (*LongLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{8}
}

func (x *LongLinkRequest) GetShorturl() *Shorturl {
	if x != nil {
		return x.Shorturl
	}
	return nil
}

type LongLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl string `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"` // короткий url вернуть
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`       // ошибка
}

func (x *LongLinkResponse) Reset() {
	*x = LongLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongLinkResponse) ProtoMessage() {}

func (x *LongLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongLinkResponse.ProtoReflect.Descriptor instead.
func (*LongLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{9}
}

func (x *LongLinkResponse) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

func (x *LongLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShortLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl *Shorturl `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *ShortLinkRequest) Reset() {
	*x = ShortLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkRequest) ProtoMessage() {}

func (x *ShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkRequest.ProtoReflect.Descriptor instead.
func (*ShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{10}
}

func (x *ShortLinkRequest) GetShorturl() *Shorturl {
	if x != nil {
		return x.Shorturl
	}
	return nil
}

type ShortLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl string `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"` // короткий url вернуть
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`       // ошибка
}

func (x *ShortLinkResponse) Reset() {
	*x = ShortLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkResponse) ProtoMessage() {}

func (x *ShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkResponse.ProtoReflect.Descriptor instead.
func (*ShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{11}
}

func (x *ShortLinkResponse) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

func (x *ShortLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserAllLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserAllLinkRequest) Reset() {
	*x = UserAllLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAllLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAllLinkRequest) ProtoMessage() {}

func (x *UserAllLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAllLinkRequest.ProtoReflect.Descriptor instead.
func (*UserAllLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{12}
}

func (x *UserAllLinkRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserAllLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`   // короткий url вернуть
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *UserAllLinkResponse) Reset() {
	*x = UserAllLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAllLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAllLinkResponse) ProtoMessage() {}

func (x *UserAllLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAllLinkResponse.ProtoReflect.Descriptor instead.
func (*UserAllLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{13}
}

func (x *UserAllLinkResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserAllLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AllLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AllLinkRequest) Reset() {
	*x = AllLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLinkRequest) ProtoMessage() {}

func (x *AllLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLinkRequest.ProtoReflect.Descriptor instead.
func (*AllLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{14}
}

func (x *AllLinkRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AllLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`   // короткий url вернуть
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *AllLinkResponse) Reset() {
	*x = AllLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLinkResponse) ProtoMessage() {}

func (x *AllLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLinkResponse.ProtoReflect.Descriptor instead.
func (*AllLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{15}
}

func (x *AllLinkResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AllLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AllUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AllUsersRequest) Reset() {
	*x = AllUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUsersRequest) ProtoMessage() {}

func (x *AllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUsersRequest.ProtoReflect.Descriptor instead.
func (*AllUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{16}
}

func (x *AllUsersRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AllUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`   // короткий url вернуть
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *AllUsersResponse) Reset() {
	*x = AllUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUsersResponse) ProtoMessage() {}

func (x *AllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUsersResponse.ProtoReflect.Descriptor instead.
func (*AllUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{17}
}

func (x *AllUsersResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AllUsersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserDelLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserDelLinkRequest) Reset() {
	*x = UserDelLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDelLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelLinkRequest) ProtoMessage() {}

func (x *UserDelLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelLinkRequest.ProtoReflect.Descriptor instead.
func (*UserDelLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{18}
}

func (x *UserDelLinkRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserDelLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *UserDelLinkResponse) Reset() {
	*x = UserDelLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDelLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelLinkResponse) ProtoMessage() {}

func (x *UserDelLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelLinkResponse.ProtoReflect.Descriptor instead.
func (*UserDelLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{19}
}

func (x *UserDelLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ReadServiceRequest) Reset() {
	*x = ReadServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServiceRequest) ProtoMessage() {}

func (x *ReadServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServiceRequest.ProtoReflect.Descriptor instead.
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{20}
}

func (x *ReadServiceRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ReadServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *ReadServiceResponse) Reset() {
	*x = ReadServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServiceResponse) ProtoMessage() {}

func (x *ReadServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServiceResponse.ProtoReflect.Descriptor instead.
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{21}
}

func (x *ReadServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SaveServiceRequest) Reset() {
	*x = SaveServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveServiceRequest) ProtoMessage() {}

func (x *SaveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveServiceRequest.ProtoReflect.Descriptor instead.
func (*SaveServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{22}
}

func (x *SaveServiceRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SaveServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *SaveServiceResponse) Reset() {
	*x = SaveServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveServiceResponse) ProtoMessage() {}

func (x *SaveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveServiceResponse.ProtoReflect.Descriptor instead.
func (*SaveServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{23}
}

func (x *SaveServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Static_CountURLs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountUrls int32 `protobuf:"varint,1,opt,name=count_urls,json=countUrls,proto3" json:"count_urls,omitempty"` // кол-во сокращённых URL в сервисе
}

func (x *Static_CountURLs) Reset() {
	*x = Static_CountURLs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Static_CountURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Static_CountURLs) ProtoMessage() {}

func (x *Static_CountURLs) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Static_CountURLs.ProtoReflect.Descriptor instead.
func (*Static_CountURLs) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Static_CountURLs) GetCountUrls() int32 {
	if x != nil {
		return x.CountUrls
	}
	return 0
}

type Static_CountUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountUsers int32 `protobuf:"varint,1,opt,name=count_users,json=countUsers,proto3" json:"count_users,omitempty"` // кол-во пользователей в сервисе
}

func (x *Static_CountUsers) Reset() {
	*x = Static_CountUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shorturl_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Static_CountUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Static_CountUsers) ProtoMessage() {}

func (x *Static_CountUsers) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Static_CountUsers.ProtoReflect.Descriptor instead.
func (*Static_CountUsers) Descriptor() ([]byte, []int) {
	return file_api_shorturl_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Static_CountUsers) GetCountUsers() int32 {
	if x != nil {
		return x.CountUsers
	}
	return 0
}

var File_api_shorturl_proto protoreflect.FileDescriptor

var file_api_shorturl_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x08, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x03, 0x64, 0x65, 0x6c, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x38, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x73, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22, 0x46,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x5b, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x75,
	0x72, 0x6c, 0x73, 0x22, 0x63, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x1a, 0x2a, 0x0a,
	0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x1a, 0x2d, 0x0a, 0x0a, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x3a, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x22, 0x55, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0f, 0x4c,
	0x6f, 0x6e, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22, 0x44, 0x0a, 0x10, 0x4c,
	0x6f, 0x6e, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x3f, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x12, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x3f, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x31, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x32, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x13, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2b,
	0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x12, 0x53,
	0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x2b, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0xc8, 0x04, 0x0a, 0x09, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x12, 0x2f, 0x0a,
	0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x08, 0x4c, 0x6f, 0x6e, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x41,
	0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_shorturl_proto_rawDescOnce sync.Once
	file_api_shorturl_proto_rawDescData = file_api_shorturl_proto_rawDesc
)

func file_api_shorturl_proto_rawDescGZIP() []byte {
	file_api_shorturl_proto_rawDescOnce.Do(func() {
		file_api_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shorturl_proto_rawDescData)
	})
	return file_api_shorturl_proto_rawDescData
}

var file_api_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_shorturl_proto_goTypes = []interface{}{
	(*Shorturl)(nil),            // 0: proto.Shorturl
	(*ShorturlResponse)(nil),    // 1: proto.ShorturlResponse
	(*Shorturls)(nil),           // 2: proto.Shorturls
	(*List)(nil),                // 3: proto.List
	(*User)(nil),                // 4: proto.User
	(*Static)(nil),              // 5: proto.Static
	(*PostRequest)(nil),         // 6: proto.PostRequest
	(*PostResponse)(nil),        // 7: proto.PostResponse
	(*LongLinkRequest)(nil),     // 8: proto.LongLinkRequest
	(*LongLinkResponse)(nil),    // 9: proto.LongLinkResponse
	(*ShortLinkRequest)(nil),    // 10: proto.ShortLinkRequest
	(*ShortLinkResponse)(nil),   // 11: proto.ShortLinkResponse
	(*UserAllLinkRequest)(nil),  // 12: proto.UserAllLinkRequest
	(*UserAllLinkResponse)(nil), // 13: proto.UserAllLinkResponse
	(*AllLinkRequest)(nil),      // 14: proto.AllLinkRequest
	(*AllLinkResponse)(nil),     // 15: proto.AllLinkResponse
	(*AllUsersRequest)(nil),     // 16: proto.AllUsersRequest
	(*AllUsersResponse)(nil),    // 17: proto.AllUsersResponse
	(*UserDelLinkRequest)(nil),  // 18: proto.UserDelLinkRequest
	(*UserDelLinkResponse)(nil), // 19: proto.UserDelLinkResponse
	(*ReadServiceRequest)(nil),  // 20: proto.ReadServiceRequest
	(*ReadServiceResponse)(nil), // 21: proto.ReadServiceResponse
	(*SaveServiceRequest)(nil),  // 22: proto.SaveServiceRequest
	(*SaveServiceResponse)(nil), // 23: proto.SaveServiceResponse
	(*Static_CountURLs)(nil),    // 24: proto.Static.CountURLs
	(*Static_CountUsers)(nil),   // 25: proto.Static.CountUsers
}
var file_api_shorturl_proto_depIdxs = []int32{
	0,  // 0: proto.Shorturls.shorturl:type_name -> proto.Shorturl
	3,  // 1: proto.User.urls:type_name -> proto.List
	0,  // 2: proto.PostRequest.shorturl:type_name -> proto.Shorturl
	1,  // 3: proto.PostResponse.result:type_name -> proto.ShorturlResponse
	0,  // 4: proto.LongLinkRequest.shorturl:type_name -> proto.Shorturl
	0,  // 5: proto.ShortLinkRequest.shorturl:type_name -> proto.Shorturl
	4,  // 6: proto.UserAllLinkRequest.user:type_name -> proto.User
	4,  // 7: proto.AllLinkRequest.user:type_name -> proto.User
	4,  // 8: proto.AllUsersRequest.user:type_name -> proto.User
	4,  // 9: proto.UserDelLinkRequest.user:type_name -> proto.User
	4,  // 10: proto.ReadServiceRequest.user:type_name -> proto.User
	4,  // 11: proto.SaveServiceRequest.user:type_name -> proto.User
	6,  // 12: proto.IShorturl.Post:input_type -> proto.PostRequest
	8,  // 13: proto.IShorturl.LongLink:input_type -> proto.LongLinkRequest
	10, // 14: proto.IShorturl.ShortLink:input_type -> proto.ShortLinkRequest
	12, // 15: proto.IShorturl.UserAllLink:input_type -> proto.UserAllLinkRequest
	14, // 16: proto.IShorturl.AllLink:input_type -> proto.AllLinkRequest
	16, // 17: proto.IShorturl.AllUsers:input_type -> proto.AllUsersRequest
	18, // 18: proto.IShorturl.UserDelLink:input_type -> proto.UserDelLinkRequest
	20, // 19: proto.IShorturl.ReadService:input_type -> proto.ReadServiceRequest
	22, // 20: proto.IShorturl.SaveService:input_type -> proto.SaveServiceRequest
	7,  // 21: proto.IShorturl.Post:output_type -> proto.PostResponse
	9,  // 22: proto.IShorturl.LongLink:output_type -> proto.LongLinkResponse
	11, // 23: proto.IShorturl.ShortLink:output_type -> proto.ShortLinkResponse
	13, // 24: proto.IShorturl.UserAllLink:output_type -> proto.UserAllLinkResponse
	15, // 25: proto.IShorturl.AllLink:output_type -> proto.AllLinkResponse
	17, // 26: proto.IShorturl.AllUsers:output_type -> proto.AllUsersResponse
	19, // 27: proto.IShorturl.UserDelLink:output_type -> proto.UserDelLinkResponse
	21, // 28: proto.IShorturl.ReadService:output_type -> proto.ReadServiceResponse
	23, // 29: proto.IShorturl.SaveService:output_type -> proto.SaveServiceResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_shorturl_proto_init() }
func file_api_shorturl_proto_init() {
	if File_api_shorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_shorturl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shorturl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShorturlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shorturls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Static); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAllLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAllLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDelLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDelLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Static_CountURLs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shorturl_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Static_CountUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shorturl_proto_goTypes,
		DependencyIndexes: file_api_shorturl_proto_depIdxs,
		MessageInfos:      file_api_shorturl_proto_msgTypes,
	}.Build()
	File_api_shorturl_proto = out.File
	file_api_shorturl_proto_rawDesc = nil
	file_api_shorturl_proto_goTypes = nil
	file_api_shorturl_proto_depIdxs = nil
}
